spring:
  datasource:
    url: jdbc:mysql://localhost/pruebagrupo2?serverTimezone=GMT-3
    username: root
    password: regusto22
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false