spring:
  datasource:
    url: jdbc:mysql://localhost/baseprueba?serverTimezone=GMT-3
    username: ${}
    password: ${}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false